### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by ZameAlex** [ZameAlex/Homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by andriisytnyk** [comment]
<h1 class="name">Donald Trump</h1>
<div class="job">The main protagonist of the Street Fighter series</div>
    <ul class="contacts">
         <li>
             <a href="https://www.fb.com/DonaldTrump" rel="author" class="facebook">
                <span>Donald Trump on facebook</span>
            </a>
         </li>
         <li>
            <a href="mailto:realDonaldTrump@whitehouse.gov" rel="author" class="mail">
                <span>Donald Trump's mail</span>
            </a>
        </li>
        <li>
            <a href="https://twitter.com/realDonaldTrump" rel="author" class="twitter">
                <span>Donald Trump in twitter</span>
            </a>
        </li>
        <li>
            <a href="https://www.instagram.com/realDonaldTrump/" rel="author" class="instagram">
                <span>Donald Trump in instagram</span>
            </a>
        </li>
    </ul>
</div>
