### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ZameAlex** [ZameAlex/Homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by andriisytnyk** [comment]
<section>
                  <h3>Languages</h3>
                  <p class="tags small">
                    <span class="language" lang="ENGLISH"><img src="usa.png"> ENGLISH</span>
                    <span class="language" lang="UKRAINIAN"><img src="ukr.png"> UKRAINIAN</span>
                    <span class="language" lang="RUSSIAN"><img src="rus.png"> RUSSIAN</span>
                  </p>
                </section>
<section class="eng" style="display: block">
                  <h3>Skills</h3>
                  <p class="tags small">KARATE <span class="nowrap">ENERGY ATTACK</span> SHORYUKEN <span class="nowrap">WALKING BAREFOOT</span> <span class="nowrap">PLAYING VIDEOGAMES</span> <span class="nowrap">DOING BURGERS</span> <span class="nowrap">MASHING POTATOES</span> <span class="nowrap">COPYWRITING ACTING VOICEOVERS</span></p>
                </section>
                <section class="eng" style="display: block">
                  <h3>Character</h3>
                  <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
                </section>
                <section class="eng" style="display: block">
                  <h3>Likes&#x1f603;</h3>
                  <p class="tags small">GI VEGETABLES BLOOD <span class="nowrap">SMALL MARSHMELLOWS</span> <span style="color: red;" class="nowrap">RED COLOR</span> <span class="nowrap">KILLED ENEMY</span></p>
                </section>
                <section class="eng" style="display: block">
                  <h3>Dislikes&#x1f61e;</h3>
                  <p class="tags small">BISONS GHOSTS SMARTPHONES <span class="nowrap">SMELL OF SEAFOOD</span> <span class="nowrap">BARBER SHOPS</span> SLEEVES</p>
                </section>
                <section class="eng" style="display: block">
                  <h3>Wants&#x1F911;</h3>
                  <p class="tags small bulleted"><span class="tag">TO BE FIT</span> <span class="tag">WRITE MORE BOOKS</span> <span class="tag">FIND A GIRLFRIEND</span> <span class="tag">TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</span></p>
                </section>
                <section class="eng" style="display: block">
                  <h3>Life lesson</h3>
                  <p class="tags small">You must defeat Sheng Long to stand a chance.</p>
                </section>
<section>
                  <h3>Skills</h3>
                  <p class="tags small">NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING</span></p>
                </section>
                <section>
                  <h3>Character</h3>
                  <p class="tags small">ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING</p>
                </section>
                <section>
                  <h3>Likes&#x1f603;</h3>
                  <p class="tags small">BILLIONS FILET-O-FISH <span class="nowrap">BIG MAC</span> CHINA <span class="nowrap">QUARTER POUNDER</span> 
                  <span class="nowrap">DIET COKE</span> TARIFFS BIBLE <span class="nowrap">ARTOF DEAL PATRIOTS</span><span class="nowrap">BEAUTIFUL MODELS</span>
                  GOLD <span class="nowrap">REAL ESTATE</span><span class="nowrap">WAR PROTESTERS</span> CONSTRUCTION <span class="nowrap">RUSSIANS BANKS</span>
                  <span class="nowrap">SPORTS WOMEN</span> MEXICO <span class="nowrap">RED HAT </span> KOREANS GOLF EVERYBODY</p>
                </section>
                <section>
                  <h3>Dislikes&#x1f61e;</h3>
                  <p class="tags small">DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS <span class="nowrap">SHITHOLE COUNTRIES</span> 
                  <span class="nowrap">UNATTRACTIVE WOMEN</span> BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT <span class="nowrap">CHRISTMAS PARTIES</span> LIBERALS</p>
                </section>
                <section>
                  <h3>Wants&#x1F911;</h3>
                  <p class="tags small bulleted"><span class="tag">BE HEALTHY</span> <span class="tag">GROW A TREE</span> <span class="tag">BUILD TRUMP AIRPORT</span> <span class="tag">HAVE A TASTE</span>
                  <span class="tag">DO A HARLEM SHAKE IN CONGRESS</span> <span class="tag">TO GOLF MORE OFTEN</span> <span class="tag">WIN ALL THE COURT SUITS</span></p>
                </section>
